### ISSUE TITLE
`drun` alias should not use docker exec

### ISSUE THREAD

**Issue by radmen** [DeSmart/laravel-vanilla#5]
Alias `drun` uses `docker exec` to run unit tests inside a running container.

I think we should use `docker-compose run` syntax to run unit tests in a separate instance.

Ref: https://github.com/DeSmart/laravel-vanilla/compare/18a03299a4...2026d8776e#diff-6707af15e231638011edbd7228677190R3

**Comment by fojuth** [comment]
Is this the proper approach?

https://github.com/DeSmart/laravel-vanilla/commit/b2c1cd44a4b987821efff63570f77ecfcb03cadf#diff-6707af15e231638011edbd7228677190

**Comment by radmen** [comment]
yup, much better
